# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a096ce48bbf6e857306ca0a6e45df7d937e747fe4b474cb38c2f023ef44259dab2059c20da74f4ee0f5319d3793c07d82533fff956444e4859575799f6f3139b

test:
  secret_key_base: bae382a698c303840ede43136d1fb943bb14ccffba307ba6567c2f3f4b0d05e78ff7b4afe108aab7f00d49b9388b981dc269ed53f053241c6c903ee8d3652b62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
